"""add more to save

Revision ID: 19d9b8261bf2
Revises: 1f3a679ef1c8
Create Date: 2022-11-30 17:05:24.837400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d9b8261bf2'
down_revision = '1f3a679ef1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.add_column(sa.Column('click1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('click2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auto1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auto2', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.drop_column('auto2')
        batch_op.drop_column('auto1')
        batch_op.drop_column('click2')
        batch_op.drop_column('click1')

    # ### end Alembic commands ###
