"""add score to save

Revision ID: 1f3a679ef1c8
Revises: f0d1648a2fcf
Create Date: 2022-11-29 16:52:45.006233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3a679ef1c8'
down_revision = 'f0d1648a2fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
