"""save table

Revision ID: f0d1648a2fcf
Revises: ea24764b41a7
Create Date: 2022-11-27 20:13:04.996077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d1648a2fcf'
down_revision = 'ea24764b41a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('save',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('save')
    # ### end Alembic commands ###
